-- MySQL Script generated by MySQL Workbench
-- Sun Oct  7 23:59:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hy` ;

-- -----------------------------------------------------
-- Schema hy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hy` DEFAULT CHARACTER SET latin1 ;
USE `hy` ;

-- -----------------------------------------------------
-- Table `hy`.`hy_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_project` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_project` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL COMMENT '项目名称',
  `price` FLOAT(15,2) NOT NULL COMMENT '项目总价',
  `start_time` INT(10) NOT NULL COMMENT '项目开工日期',
  `days` INT(10) NOT NULL COMMENT '项目竣工日期',
  `create_time` INT(10) NOT NULL,
  `number` INT(10) UNSIGNED NOT NULL COMMENT '项目编号',
  `update_time` INT(10) UNSIGNED NOT NULL,
  `remark` VARCHAR(45) NOT NULL COMMENT '备注',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '项目名称';


-- -----------------------------------------------------
-- Table `hy`.`hy_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_manager` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_manager` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL COMMENT '项目经理姓名',
  `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '项目经理联系方式',
  `create_time` INT(10) UNSIGNED NOT NULL,
  `update_time` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '项目经理';


-- -----------------------------------------------------
-- Table `hy`.`hy_bids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_bids` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_bids` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL COMMENT '标段名称',
  `p_id` INT(10) UNSIGNED NOT NULL COMMENT '项目ID',
  `m_id` INT(10) UNSIGNED NOT NULL,
  `create_time` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `update_time` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  `remark` VARCHAR(45) NOT NULL COMMENT '备注',
  `price` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY USING BTREE (`id`),
  INDEX `bids_index_idx` (`p_id` ASC),
  INDEX `bids_index2_idx` (`m_id` ASC),
  CONSTRAINT `bids_index`
    FOREIGN KEY (`p_id`)
    REFERENCES `hy`.`hy_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bids_index2`
    FOREIGN KEY (`m_id`)
    REFERENCES `hy`.`hy_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '标段';


-- -----------------------------------------------------
-- Table `hy`.`hy_classify`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_classify` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_classify` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL COMMENT '主类名称',
  `create_time` INT(10) UNSIGNED NOT NULL,
  `update_time` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '主类';


-- -----------------------------------------------------
-- Table `hy`.`hy_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_category` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL COMMENT '详细分类名称',
  `c_id` INT(10) UNSIGNED NOT NULL COMMENT '分类ID',
  `create_time` INT(10) UNSIGNED NOT NULL COMMENT '创建时间',
  `update_time` INT(10) UNSIGNED NOT NULL COMMENT '更新时间',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `cate_index_idx` (`c_id` ASC),
  CONSTRAINT `cate_index`
    FOREIGN KEY (`c_id`)
    REFERENCES `hy`.`hy_classify` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '详细分类';


-- -----------------------------------------------------
-- Table `hy`.`hy_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_company` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_company` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL COMMENT '供应商名称',
  `account` VARCHAR(25) NULL DEFAULT NULL COMMENT '供应商付款账号',
  `create_time` INT(10) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT '电话号码',
  `contacts` VARCHAR(20) NULL DEFAULT NULL COMMENT '联络人',
  `bank_name` VARCHAR(50) NOT NULL,
  `remark` VARCHAR(45) NULL DEFAULT NULL COMMENT '备注',
  `update_time` INT(10) UNSIGNED NOT NULL,
  `c_id` INT(10) UNSIGNED NOT NULL COMMENT '主类ID',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `com_index_idx` (`c_id` ASC),
  CONSTRAINT `com_index`
    FOREIGN KEY (`c_id`)
    REFERENCES `hy`.`hy_classify` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '供应商名称';


-- -----------------------------------------------------
-- Table `hy`.`hy_contract_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_contract_manager` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_contract_manager` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `conMC` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '资料是否齐全',
  `conMR` VARCHAR(45) NOT NULL COMMENT '资料不全备注',
  `conMN` VARCHAR(45) NOT NULL COMMENT '经办人姓名',
  `conMP` VARCHAR(45) NOT NULL COMMENT '经办人电话',
  `delete` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '合同是否作废',
  `borrow` TINYINT(3) UNSIGNED NULL DEFAULT '0' COMMENT '合同借阅',
  `borrow_remark` VARCHAR(45) NOT NULL COMMENT '合同借阅备注',
  `create_time` INT(10) UNSIGNED NOT NULL,
  `total` INT(10) UNSIGNED NOT NULL COMMENT '合同份数',
  `keep` INT(10) UNSIGNED NOT NULL COMMENT '合同公司留存份数',
  `confirm` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '合同是否盖章',
  `delete_remark` VARCHAR(45) NOT NULL COMMENT '合同作废备注',
  `update_time` INT(10) UNSIGNED NOT NULL,
  `vertify` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '合同审核是否通过',
  `save` TINYINT(3) UNSIGNED NOT NULL COMMENT '合同存档确认',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '合同管理';


-- -----------------------------------------------------
-- Table `hy`.`hy_contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_contract` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_contract` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `c_id` INT(10) UNSIGNED NOT NULL COMMENT '供应商名称ID',
  `price` FLOAT(15,2) NULL DEFAULT NULL COMMENT '总价',
  `create_time` INT(10) UNSIGNED NOT NULL,
  `start_time` INT(10) UNSIGNED NOT NULL COMMENT '合同开始日期',
  `end_time` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '合同截止日期',
  `remark` VARCHAR(200) NULL DEFAULT NULL COMMENT '备注',
  `p_id` INT(10) UNSIGNED NOT NULL COMMENT '项目ID',
  `category_id` INT(10) UNSIGNED NOT NULL COMMENT '次级分类ID',
  `name` VARCHAR(45) NOT NULL COMMENT '合同名称',
  `b_id` INT(10) UNSIGNED NOT NULL COMMENT '标段ID',
  `update_time` INT(10) UNSIGNED NOT NULL,
  `number` INT(10) UNSIGNED NOT NULL COMMENT '合同编号',
  `m_id` INT(10) UNSIGNED NOT NULL COMMENT '合同管理ID',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `con_index2_idx` (`p_id` ASC),
  INDEX `con_index3_idx` (`b_id` ASC),
  INDEX `con_index4_idx` (`m_id` ASC),
  INDEX `con_index5_idx` (`category_id` ASC),
  CONSTRAINT `con_index`
    FOREIGN KEY (`c_id`)
    REFERENCES `hy`.`hy_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `con_index2`
    FOREIGN KEY (`p_id`)
    REFERENCES `hy`.`hy_project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `con_index3`
    FOREIGN KEY (`b_id`)
    REFERENCES `hy`.`hy_bids` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `con_index4`
    FOREIGN KEY (`m_id`)
    REFERENCES `hy`.`hy_contract_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `con_index5`
    FOREIGN KEY (`category_id`)
    REFERENCES `hy`.`hy_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '合同';


-- -----------------------------------------------------
-- Table `hy`.`hy_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_team` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_team` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL COMMENT '组长姓名',
  `user_phone` VARCHAR(45) NOT NULL COMMENT '组长电话',
  `remark` VARCHAR(45) NOT NULL COMMENT '备注',
  `creat_time` INT(11) NOT NULL,
  `update_time` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COMMENT = '人员工资-五大班组';


-- -----------------------------------------------------
-- Table `hy`.`hy_reimbursement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hy`.`hy_reimbursement` ;

CREATE TABLE IF NOT EXISTS `hy`.`hy_reimbursement` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `c_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '供应商名称ID',
  `create_time` INT(10) NOT NULL,
  `price` FLOAT(15,2) NOT NULL DEFAULT '0.00' COMMENT '金额合计',
  `remark` VARCHAR(100) NULL DEFAULT NULL COMMENT '备注',
  `b_id` INT(10) UNSIGNED NOT NULL COMMENT '标段ID',
  `update_time` INT(10) UNSIGNED NOT NULL,
  `type` INT(3) UNSIGNED NULL DEFAULT '0' COMMENT '报销单类型：1、材料、租赁、分包项目 2、人员工资 3、费用报销 4、无合同报销',
  `t_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '班组ID',
  PRIMARY KEY USING BTREE (`id`),
  INDEX `reim_index1_idx` (`c_id` ASC),
  INDEX `reim_index2_idx` (`b_id` ASC),
  INDEX `reim_index3_idx` (`t_id` ASC),
  CONSTRAINT `rei_index1`
    FOREIGN KEY (`c_id`)
    REFERENCES `hy`.`hy_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rei_index2`
    FOREIGN KEY (`b_id`)
    REFERENCES `hy`.`hy_bids` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rei_index4`
    FOREIGN KEY (`t_id`)
    REFERENCES `hy`.`hy_team` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf16
COMMENT = '报销单';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
